In [1]:
import streamlit as st
from pathlib import Path
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

In [2]:

df = pd.read_csv("/Users/toby/Dev/lionel-app/data/charts_1_25.csv")

In [8]:
pred_var = 'y_LGBMRegressor_no_exog'
df_plot = df[df[pred_var].notna()]

In [14]:
df_plot

,name,opponent_team_name,is_home,season,gameweek,team_name,position,y,y_Naive,y_LGBMRegressor_no_exog,y_LSTMWithReLU
38,Aaron Ramsdale,Wolves,True,25,1,Arsenal,GK,NaN,0.0,0.149775,0.0
39,Aaron Ramsdale,Aston Villa,False,25,2,Arsenal,GK,NaN,0.0,0.629855,0.0
40,Aaron Ramsdale,Brighton,True,25,3,Arsenal,GK,NaN,0.0,1.117793,0.0
41,Aaron Ramsdale,Tottenham,False,25,4,Arsenal,GK,NaN,0.0,1.141988,0.0
42,Aaron Ramsdale,Manchester City,False,25,5,Arsenal,GK,NaN,0.0,1.439281,0.0
...,...,...,...,...,...,...,...,...,...,...,...
35691,Yerson Mosquera,Southampton,True,25,11,Wolves,DEF,NaN,0.0,1.738830,0.0
35692,Yerson Mosquera,Fulham,False,25,12,Wolves,DEF,NaN,0.0,2.459075,0.0
35693,Yerson Mosquera,Bournemouth,True,25,13,Wolves,DEF,NaN,0.0,2.055266,0.0
35694,Yerson Mosquera,Everton,False,25,14,Wolves,DEF,NaN,0.0,2.135080,0.0
35695,Yerson Mosquera,West Ham,False,25,15,Wolves,DEF,NaN,0.0,1.822735,0.0

In [13]:
df_plot.groupby('name')[[pred_var, 'value']].mean()

KeyError: "Columns not found: 'value'"

# Team level charts

In [18]:
df_team = pd.read_csv("/Users/toby/Dev/lionel-app/data/team_selection_1_25.csv")
df_team.head()

,unique_id,team_name,position,value,pred_Naive,pred_LGBMRegressor_no_exog,pred_LSTMWithReLU,picked_Naive,captain_Naive,first_xi_Naive,season,picked_time,picked_LGBMRegressor_no_exog,captain_LGBMRegressor_no_exog,first_xi_LGBMRegressor_no_exog,picked_LSTMWithReLU,captain_LSTMWithReLU,first_xi_LSTMWithReLU
0,Alexander Isak,Newcastle,FWD,84,14.0,4.469617,2.0,1.0,0,1.0,24,2024-08-04 10:09:23.604859,0.0,0,NaN,0.0,0,NaN
1,André Onana,Manchester Utd,GK,50,7.0,3.120548,2.0,1.0,0,1.0,24,2024-08-04 10:09:23.604859,0.0,0,NaN,0.0,0,NaN
2,Bruno Guimarães Rodriguez Moura,Newcastle,MID,58,16.0,5.171441,2.0,1.0,0,1.0,24,2024-08-04 10:09:23.604859,1.0,0,1.0,0.0,0,NaN
3,Dejan Kulusevski,Tottenham,MID,67,16.0,2.760795,2.0,1.0,0,1.0,24,2024-08-04 10:09:23.604859,0.0,0,NaN,0.0,0,NaN
4,Diogo Dalot Teixeira,Manchester Utd,DEF,52,15.0,3.661784,1.0,1.0,0,1.0,24,2024-08-04 10:09:23.604859,0.0,0,NaN,0.0,0,NaN

In [19]:
df_team.columns

Index(['unique_id', 'team_name', 'position', 'value', 'pred_Naive',
       'pred_LGBMRegressor_no_exog', 'pred_LSTMWithReLU', 'picked_Naive',
       'captain_Naive', 'first_xi_Naive', 'season', 'picked_time',
       'picked_LGBMRegressor_no_exog', 'captain_LGBMRegressor_no_exog',
       'first_xi_LGBMRegressor_no_exog', 'picked_LSTMWithReLU',
       'captain_LSTMWithReLU', 'first_xi_LSTMWithReLU'],
      dtype='object')

In [24]:
pred_var = "LGBMRegressor_no_exog"
df_team[df_team[f"picked_{pred_var}"] == 1].head()

,unique_id,team_name,position,value,pred_Naive,pred_LGBMRegressor_no_exog,pred_LSTMWithReLU,picked_Naive,captain_Naive,first_xi_Naive,season,picked_time,picked_LGBMRegressor_no_exog,captain_LGBMRegressor_no_exog,first_xi_LGBMRegressor_no_exog,picked_LSTMWithReLU,captain_LSTMWithReLU,first_xi_LSTMWithReLU
2,Bruno Guimarães Rodriguez Moura,Newcastle,MID,58,16.0,5.171441,2.0,1.0,0,1.0,24,2024-08-04 10:09:23.604859,1.0,0,1.0,0.0,0,NaN
7,Jarell Quansah,Liverpool,DEF,40,15.0,3.777053,0.0,1.0,0,1.0,24,2024-08-04 10:09:23.604859,1.0,0,0.0,0.0,0,NaN
10,Phil Foden,Manchester City,MID,85,15.0,6.284066,3.0,1.0,0,1.0,24,2024-08-04 10:09:23.604859,1.0,0,1.0,0.0,0,NaN
12,Guglielmo Vicario,Tottenham,GK,53,6.0,4.000374,2.0,1.0,0,0.0,24,2024-08-04 10:09:23.604859,1.0,0,1.0,0.0,0,NaN
89,Benjamin White,Arsenal,DEF,61,2.0,5.023394,4.0,0.0,0,NaN,24,2024-08-04 10:09:23.604859,1.0,0,1.0,1.0,0,1.0

In [34]:
fig = go.Figure()
df_not_picked = df_team[df_team[f"picked_{pred_var}"] == 0]
df_picked = df_team[df_team[f"picked_{pred_var}"] == 1]

In [39]:
fig.add_trace(go.Scatter(
    x=df_not_picked[df_not_picked[f"picked_{pred_var}"] == 0].value,
    y=df_not_picked[df_not_picked[f"picked_{pred_var}"] == 0][f"pred_{pred_var}"],
    marker=dict(
        color='#9fbbe3', 
    ),
    mode='markers',
    customdata=df_not_picked[["unique_id", "team_name", f"pred_{pred_var}"]],
            hovertemplate="<b>%{customdata[0]}</b>"
            + "<br><br><b>Team:</b> %{customdata[1]}"
            + "<br><b>Forecasted Points:</b> %{customdata[2]}"
            + "<extra></extra>",
))

In [40]:
fig.add_trace(go.Scatter(
            x=df_picked.value,
            y=df_picked[f"pred_{pred_var}"],
            marker=dict(
                color='#4B5563', 
            ),
            mode='markers',
            customdata=df_picked[["unique_id", "team_name", f"pred_{pred_var}"]],
            hovertemplate="<b>%{customdata[0]}</b>"
            + "<br><br><b>Team:</b> %{customdata[1]}"
            + "<br><b>Forecasted Points:</b> %{customdata[2]}"
            + "<extra></extra>",))

fig.update_layout(
    autosize=False,
    width=700,
    height=800,
    showlegend=False,
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
    xaxis_title="Player Value (as of previous GW)",
    yaxis_title="Forecasted Points",
    yaxis_visible=True, 
    yaxis_showticklabels=False,
    xaxis_visible=True, 
    xaxis_showticklabels=False,
    font=dict(
        family="sans-serif",
        color="#4B5563"
    )
)